### PR TITLE
Bump version to 3.4.1

### PR DESCRIPTION
**Pull request by MouettE-SC**
Bump version to 3.4.1

### CODE REVIEW

**Comment by ghost** [comment]
The script works now?

**Comment by MouettE-SC** [comment]
OK this one is ready

**Comment by ghost** [comment]
Did it build successfully in clean chroot?

**Comment by MouettE-SC** [comment]
> The script works now?

yes ! We'll now for sure on the next release.

**Comment by MouettE-SC** [comment]
Make sure to delete the release branch once this is merged on master.

**Comment by MouettE-SC** [comment]
> Did it build successfully in clean chroot?

Yes

**Comment by ghost** [comment]
Alright let me reproduce this build!

**Comment by ghost** [comment]
Totally forgot about merging this haha

**Pull request merged**
